language: node_js
node_js:
- 7.0.0
sudo: false
script:
- npm test
branches:
  only: master
after_success:
- git remote add deploy $REPO
- git push deploy
before_install:
- echo -e "Host $SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_62da1aba3443_key -iv $encrypted_62da1aba3443_iv -in pat-bot.pem.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
