export const FETCH_COMMANDS = 'FETCH_COMMANDS';
export const FETCH_COMMANDS_PENDING = 'FETCH_COMMANDS_PENDING';
export const FETCH_COMMANDS_FULFILLED = 'FETCH_COMMANDS_FULFILLED';
export const FETCH_COMMANDS_REJECTED = 'FETCH_COMMANDS_REJECTED';
